name="micro-app-dev"
type = "webpack"
workers_dev = true

account_id = ""
zone_id = ""

[env.assets]
name = "micro-app-assets"
route = "fn2.dev/mjs/*"
webpack_config = "clouds/cloudflare/webpack.assets.js"

[env.server]
name = "micro-app-server"
route = "fn2.dev/*"
webpack_config = "clouds/cloudflare/webpack.server.js"
